### ISSUE TITLE
Sugestion - optional wss:// support

### ISSUE THREAD

**Issue by ablaszkiewicz** [unkn0w/proxer#3]
I have run into an issue where I wanted my service to support websockets. Proxer doesn't support this out of the box.
I don't know bash so my solution isn't probably the cleanest one but I just wanted to share a suggestion. My modification allows optional `wss://` connections.

So I've made a change in a bash script
![image](https://user-images.githubusercontent.com/54682207/162787823-59d11808-0c21-41f5-9e4d-8ea725d668f3.png)

And now in config file I am able to specify which rows should support `wss://`
![image](https://user-images.githubusercontent.com/54682207/162788140-5bc6ce4e-5096-4886-a671-345995079421.png)

As I mentioned above I don't know bash so it's a poor quality code but it would be nice to see this feature implemented by someone who can actually use bash and linux.

**Comment by unkn0w** [comment]
Done - support for websockets is now avalilable in Proxer.

Just fetch new version of code, build new image and run it :)
